### ISSUE TITLE
Issues Getting Implicit working on Docker + Airflow

### ISSUE THREAD

**Issue by murphystout** [benfred/implicit#475] opened 2021-09-06 05:17 UTC
Wondering if anyone can help me out here.  I'm getting consistent errors trying to load up implicit within my docker container.

This is the error log:

Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sv55jqbt/implicit/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-7x9d6dv7/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-sv55jqbt/implicit/

I read your other similar response, and I do have GCC installed on the docker, along with build-essential.  I'm wondering if there is a handy reference for any other stacks I need for a linux/docker install.

Thank you!

**Comment by benfred** [comment] 2021-09-09 04:08
Can you share the full log? Or a dockerfile that reproduces this?

**Comment by benfred** [comment] 2022-01-03 21:02
Closing since I didn't hear back from you - feel free to reopen if this is still a problem

**Closed by benfred** 2022-01-03 21:02 UTC
