### ISSUE TITLE
What do we pass as input to mean_average_precision_at_k???

### ISSUE THREAD

**Issue by medoidai** [benfred/implicit#340] opened 2020-03-24 09:04 UTC
@ita9naiwa @benfred

For the following parameters of the function mean_average_precision_at_k:

```
train_user_items : csr_matrix
        Sparse matrix of user by item that contains elements that were used in training the model
test_user_items : csr_matrix
        Sparse matrix of user by item that contains withheld elements to test on
```

Assuming I have two uses cases where my data are implicit either 0s/1s or 0s/#interactions:

In the first approach whenever there is an interaction between user-item we encode it as 1 and all the unknown interactions are encoded as 0 in the csr_matrix.

In the second approach whenever there is an interaction we encode it as #interactions which is the number of times user-item interacted and all unknown interactions are encoded as 0 in the csr_matrix.

For both the above approaches when training and evaluating the results which of the following two code snippets are correct?

```
train_item_users = csr_matrix with 0s/1s or 0s/#interactions
test_item_users = csr_matrix with 0s/1s or 0s/#interactions

weighted_train_item_users = train_item_users * alpha
weighted_test_item_users = test_item_users * alpha

model.fit(weighted_train_item_users)

score = implicit.evaluation.mean_average_precision_at_k (model, weighted_train_item_users.T.csr(), weighted_test_item_users.T.csr(), k=10) 
```

or

```
train_item_users = csr_matrix with 0s/1s or 0s/#interactions
test_item_users = csr_matrix with 0s/1s or 0s/#interactions

weighted_train_item_users = train_item_users * alpha

model.fit(weighted_train_item_users)

score = implicit.evaluation.mean_average_precision_at_k (model, train_item_users.T.csr(), test_item_users.T.csr(), k=10) 
```

So, the major question is do we pass in the mean_average_precision_at_k the weighted or the original data before weighting?

Thank you!

**Comment by ita9naiwa** [comment] 2020-03-31 03:10
Duplicate of #337

**Closed by ita9naiwa** 2020-03-31 03:10 UTC

**Comment by medoidai** [comment] 2020-03-31 06:54
Thank you @ita9naiwa! Efstathios.
