### ISSUE TITLE
Recommend doesn't match with recommend_all

### ISSUE THREAD

**Issue by allexch** [benfred/implicit#299] opened 2019-11-28 08:42 UTC
Hello!

I am facing with a strange issue: array of items, returning by "recommend" function for a single user N is not the same with Nth array returning by "recommend_all" function. See code below:

model = implicit.bpr.BayesianPersonalizedRanking(factors=100)
model.fit(mat_train)
recsall = model.recommend_all(mat_train.T)
recsall[0]

recs = model.recommend(0, mat_train.T)
recs

here recsall[0] <> recs

Model here doesn't matter. Same behaviour in ALS.
Could anyone explain?

**Comment by benfred** [comment] 2019-12-15 17:19
Think this is a duplicate of https://github.com/benfred/implicit/issues/266

**Closed by benfred** 2019-12-15 17:19 UTC

**Comment by XUJiahua** [comment] 2020-02-11 07:47
I got the same issue, and finally figured it out.

From the API signatures, we can learn:
1. model.fit() accepts item_users sparse matrix.
2. model.recommend() accepts user_items sparse matrix.

Pitfall here is that we use item_users.T in model.recommend(). Take ALS as an example, https://github.com/benfred/implicit/blob/v0.4.2/implicit/recommender_base.pyx#L166, sparse matrix’s indices is used in recommend(). However item_users.T.indices and user_items.indices are not equal. After transposing, sparse matrix’s indices has no change.

Either way below is OK:
1. construct a brand new user_items sparse matrix from raw data
2. pass filter_already_liked_items=False in both recommend() and recommend_all()
